name: PHP CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Current Files
        run: dir

      - name: Create Fake Production Folder
        run: |
          if not exist "E:\xampp\htdocs\fake_production" mkdir "E:\xampp\htdocs\fake_production"

      - name: Deploy Files
        run: |
          robocopy . "E:\xampp\htdocs\fake_production" /E

      - name: Deployment Success
        run: echo Deployment Completed