name: PHP CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: dir

      - name: Create Fake Production Folder
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "E:\xampp\htdocs\fake_production"

      - name: Deploy Files
        shell: powershell
        run: |
          Copy-Item -Path * -Destination "E:\xampp\htdocs\fake_production" -Recurse -Force

      - name: Success Message
        run: echo Deployment Successful